daemon off;
master_process off;
error_log /dev/stderr;


events {
    worker_connections 1024;
}

http {

    types_hash_max_size 2048;
    types_hash_bucket_size 128;

     # ВЫКЛЮЧАЕМ ЛОГИ полностью

    access_log /dev/stdout;  # access логи в консоль


    server {
        listen 3000;
        server_name localhost;
        root C:/Users/user/WebstormProjects/untitled;
        index index.html;

        types {
            text/html html;
            text/css css;
            application/javascript js;
        }

        gzip on;
        gzip_types text/html application/javascript text/css;

          location / {
            try_files $uri $uri/ /index.html;
        }
    }
}
